# Generated by Django 6.1.2 on 2026-10-06 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department_chair', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('main_info', models.TextField()),
                ('contacts', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('coordinator_name', models.CharField(max_length=100)),
                ('coordinator_contact', models.CharField(max_length=100)),
                ('disciplines_list', models.ManyToManyField(related_name='programs', to='economics.discipline')),
                ('issuing_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='economics.department')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=300)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='economics.department')),
            ],
        ),
    ]
