# Generated by Django 5.x

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('economics', '0002_exchangeprogram'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            INSERT INTO economics_exchangeprogram (university, languages, places, deadline, description) VALUES
            ('Uniwersytet Warszawski, Польща', 'польська, англійська', '5', '2026-11-15', 'Один з найбільших і найпрестижніших університетів Польщі.'),
            ('KU Leuven (Бельгія)', 'English', '2 місця', '2026-12-01', 'Провідний європейський дослідницький університет.'),
            ('Vilnius University, Литва', 'англійська', 'до 4', '2026-10-20', 'Найстаріший університет у країнах Балтії.'),
            ('Uniwersytet Jagielloński, Польща', 'Польська, Англійська', '3', '2026-11-15', 'Один з найстаріших університетів Європи, розташований у Кракові.'),
            ('University of Tartu - Естонія', 'англійська, естонська', '2', '2027-01-10', 'Національний університет Естонії, відомий своїми дослідженнями.'),
            ('Masaryk University, Чехія', 'англійська', '1 місце', '2026-09-30', 'Другий за величиною університет Чехії, розташований у Брно.');
            """,
            reverse_sql="DELETE FROM economics_exchangeprogram;"
        )
    ]
