# Generated by Django 6.1.2 on 2026-10-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economics', '0003_exchange_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeprogram',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
