# Generated by Django 5.x

from django.db import migrations
import re

def split_university(apps, schema_editor):
    ExchangeProgram = apps.get_model('economics', 'ExchangeProgram')
    for program in ExchangeProgram.objects.all():
        val = program.university
        # Try finding country in parentheses
        match = re.search(r'\(([^)]+)\)', val)
        if match:
            program.country = match.group(1).strip()
            program.university = val[:match.start()].strip()
        else:
            # Try splitting by comma or dash
            parts = re.split(r'[,|-]', val)
            if len(parts) > 1:
                program.country = parts[-1].strip()
                program.university = parts[0].strip()
        program.save()

def revert_split(apps, schema_editor):
    ExchangeProgram = apps.get_model('economics', 'ExchangeProgram')
    for program in ExchangeProgram.objects.all():
        if program.country:
            program.university = f"{program.university}, {program.country}"
            program.country = None
        program.save()

class Migration(migrations.Migration):

    dependencies = [
        ('economics', '0004_exchangeprogram_country'),
    ]

    operations = [
        migrations.RunPython(split_university, revert_split)
    ]
