# Generated by Django 5.x

from django.db import migrations
import re

def clean_places(apps, schema_editor):
    ExchangeProgram = apps.get_model('economics', 'ExchangeProgram')
    for program in ExchangeProgram.objects.all():
        val = program.places
        match = re.search(r'\d+', val)
        if match:
            program.places = match.group(0)
        program.save()

def revert_places(apps, schema_editor):
    pass # Data loss here, original strings ("до 4", "2 місця") are lost. Document in ANSWERS.md

class Migration(migrations.Migration):

    dependencies = [
        ('economics', '0005_split_university'),
    ]

    operations = [
        migrations.RunPython(clean_places, revert_places)
    ]
