# Generated by Django 6.1.2 on 2026-10-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economics', '0006_clean_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeprogram',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exchangeprogram',
            name='places',
            field=models.IntegerField(),
        ),
    ]
